etkinlik/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("haydi.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

haydi/urls.py
from django import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
urlpatterns = [
path('', views.home, name='home'),
path('<int:year>/<str:month>/', views.home, name='home'),
path('mekan_ekle/', views.mekanekle, name='mekanekle'),
path('get-ilceler/<int:sehir_id>/', views.get_ilceler, name='get_ilceler'),   
path('eventlist', views.eventlist, name='eventlist'),
path('update_profile', views.update_profile, name='update_profile'),
path('eventdetail/<slug:slug>', views.eventdetail, name='eventdetail'),
path('yer_listesi/', views.yer_listesi, name='yer_listesi'), 
path('yer_detay/<int:pk>', views.yer_detay, name='yer_detay'),
path('arama_sonuclari/', views.arama_sonuclari, name='arama_sonuclari'),
path('etkinlik_ekle', views.etkinlik_ekle, name='etkinlik_ekle'),
path('get-mekanlar/<int:ilce_id>/', views.get_mekanlar, name='get_mekanlar'),
path('register/', views.register, name='register'),
path('login/', views.login_view, name='login'),
path('logout/', views.custom_logout, name='logout'),
path('my_profile/', views.my_profile, name='my_profile'),
path('show_profile/<str:username>/', views.show_profile, name='show_profile'),
path('katilimci_ol/<slug:slug>/', views.katilimci_ol, name='katilimci_ol'),
path('katilmayi_birak/<slug:slug>/', views.katilmayi_birak, name='katilmayi_birak'),
path('etkinlik/<slug:slug>/sil/', views.etkinlik_sil, name='etkinlik_sil'),
path('etkinlik_düzenle/<slug:slug>', views.etkinlik_düzenle, name='etkinlik_düzenle'),
path('mekan_güncelle/<int:mekan_id>', views.mekan_guncelle, name='mekan_güncelle'),
path('mekanlar/', views.sahip_oldugunuz_mekanlar, name='mekanlar'),
path('etkinliklerim/', views.etkinliklerim, name='etkinliklerim'),
path('etkinlikten_at/<slug:slug>/<int:pk>', views.etkinlikten_at, name='etkinlikten_at'),
path('yorum_yap/<slug:slug>/', views.yorum_yap, name='yorum_yap'),
path('yorum_sil/<int:pk>', views.yorum_sil, name='yorum_sil'),
path('cevap_ver/<int:pk>/<slug:slug>', views.cevap_ver, name='cevap_ver'),
path('mekan_sil/<int:pk>', views.mekan_sil, name='mekan_sil'),
path('mekani_ac/<int:pk>', views.mekani_ac, name='mekani_ac'),
path('mekani_kapat/<int:pk>', views.mekani_kapat, name='mekani_kapat'),
path('olumlu_oy/<int:pk>/', views.olumlu_oy, name='olumlu_oy'),
path('olumsuz_oy/<int:pk>/', views.olumsuz_oy, name='olumsuz_oy'),
path('mekan_begeni_durumu/<int:pk>/', views.mekan_begeni_durumu, name='mekan_begeni_durumu'),
path('bildirim_acildi/', views.bildirim_acildi, name='bildirim_acildi'),
path('home', views.home, name='home'),
path('gundetay/<int:day>-<str:month>-<int:year>/', views.gundetay, name='gundetay'),
path('engelle/<int:pk>', views.engelle, name='engelle'),
path('takip_et/<int:pk>', views.takip_et, name='takip_et'),
path('takipciyi_cikar/<int:pk>', views.takipciyi_cikar, name='takipciyi_cikar'),
path('pozitif_oy/<int:pk>',views.profil_pozitif_oy,name="pozitif_oy"),
path('negatif_oy/<int:pk>',views.profil_negatif_oy,name="negatif_oy"),

# path('gundetay/', views.gundetay, name='gundetay'),
# path('gundetay/<str:selected_date>/', views.gundetay_selected, name='gundetay_selected'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haydi/models.py
import datetime
import os
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from cities_light.models import SubRegion, Region
from ckeditor.fields import RichTextField

from django.utils.crypto import get_random_string

def user_directory_path(instance, filename):
    # Dosya adını kullanıcı adı ile değiştir
    ext = filename.split('.')[-1]
    filename = f'{instance.username}_{timezone.now().strftime("%Y-%m-%d-%H-%M-%S")}.{ext}'

    # Dosyanın kaydedileceği klasörü belirle
    folder = f'profile_pics/{instance.username}'

    # Klasörü oluştur
    os.makedirs(folder, exist_ok=True)

    # Tam dosya yolu
    return os.path.join(folder, filename)

    
class Mekan(models.Model):
    adi = models.CharField('Mekan Adı', max_length=20)
    adres = models.CharField(max_length=300)
    telefon_numarasi = models.CharField('Telefon', max_length=11)
    webadresi = models.URLField('Website Adresi')
    email = models.EmailField('Email Adresi')
    sehir = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True, related_name='sehir')
    ilce = models.ForeignKey(SubRegion, on_delete=models.SET_NULL, null=True, blank=True)
    aciklama = models.TextField('Mekan Açıklaması', null=True, blank=True)
    olusturan = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    onayli = models.BooleanField('Onaylı', default=True) # default False olacak deneme için true dedim
    onay_tarihi = models.DateTimeField('Onay Tarihi', null=True, blank=True)
    silindi = models.BooleanField('Silindi',default='False')
    acik = models.BooleanField('Etkinliğe Açık',default=False)
    olumlu_oy = models.PositiveIntegerField(default=0)
    olumlu_oy_kullananlar = models.ManyToManyField(User, related_name='olumlu_oylar',null=True,blank=True)
    olumsuz_oy = models.PositiveIntegerField(default=0)
    olumsuz_oy_kullananlar = models.ManyToManyField(User, related_name='olumsuz_oylar',null=True,blank=True)

    def save(self, *args, **kwargs):
        if self.onayli and not self.onay_tarihi:
            self.onay_tarihi = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.adi

class Event(models.Model):
    ad = models.CharField('Etkinlik Adı', max_length=50)
    baslik = models.CharField('Baslik', max_length=50, null=True, blank=True)
    slug = models.SlugField(unique=True, max_length=100, null=True, blank=True)
    saat = models.TimeField('Saat', null=False, blank=False)
    gün = models.DateTimeField('Etkinlik Günü')
    katilimcilar = models.ManyToManyField(User, related_name='katildigi_etkinlikler', blank=True)
    katilimci_kontrol = models.BooleanField(default=False)
    kontenjan = models.PositiveIntegerField(default=0,null=True,blank=True)
    mekan = models.ForeignKey(Mekan, blank=True, null=True,related_name='etkinlikler', on_delete=models.CASCADE)
    açiklama = RichTextField()
    yönetici = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name='yönetici_event_set')
    silindi = models.BooleanField(default=False)
    takipçiye_özel = models.BooleanField(default=False)
    def get_katilimcilar(self):
        return self.katilimcilar.all()
    def __str__(self):
        return f"{self.ad} ({self.gün.strftime('%d.%m.%Y %H:%M')})"

    def save(self, *args, **kwargs):
        if not self.baslik:  # Başlık boşsa (yeni etkinlik)
            self.baslik = slugify(self.ad)  # Etkinlik adından başlığı oluştur
        if not self.slug:  # Slug boşsa (yeni etkinlik)
            slug = slugify(self.baslik)
            random_string = get_random_string(length=4)  # Rastgele bir dize oluştur
            self.slug = f"{slug}-{random_string}"  # Slug'a rastgele dizeyi ekle
        # if self.katilimci_kontrol:
        #     self.katilimci_sayisi = self.katilimcilar.count()
        super(Event, self).save(*args, **kwargs)
    
    def günü_gecmis(self):
        now = datetime.now()
        event_datetime = datetime.combine(self.gün, self.saat)
        return event_datetime < now
class Yorum(models.Model):
    yorum = models.CharField(max_length=255)
    yorum_sahibi = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='yorumlar')
    silindi = models.BooleanField(default=False)
    def event_ad(self):
        return self.event.ad
class YorumCevap(models.Model):
    cevap = models.CharField(max_length=255,blank=True,null=True)
    yorum = models.ForeignKey(Yorum, on_delete=models.DO_NOTHING, related_name='cevaplar',null=True,blank=True)
    cevapsahibi = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    silindi = models.BooleanField(default=False)

    def __str__(self):
        return self.cevap


from django.contrib.auth.models import Permission
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    ad = models.CharField(max_length=20, verbose_name='ad')
    soyad = models.CharField(max_length=20)
    profile_img = models.ImageField(upload_to=user_directory_path)
    email = models.EmailField(null=True, blank=True)
    telefon = models.CharField(max_length=11, blank=True, null=True)
    kayit_tarihi = models.DateTimeField(auto_now_add=True)
    katildigi_etkinlikler = models.ManyToManyField(Event, related_name='katilimcilar_profil', blank=True)
    olusturdugu_etkinlikler = models.ManyToManyField(Event, related_name='olusturan_profil', blank=True)
    bildirimler = models.ManyToManyField('Bildirim', related_name='bildirim_alani1', blank=True,null=True)
    bildirim_sayisi = models.PositiveIntegerField(default = 0 ,null=True,blank=True,)
    engelli_listesi = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='engelli')
    takip_ettiklerim = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='takip_edilen')
    takipçiler = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='takipçilerim')
    pozitif_oylar = models.ManyToManyField(User, related_name='pozitif_oylar',null=True,blank=True)
    negatif_oylar = models.ManyToManyField(User, related_name='negatif_oylar',null=True,blank=True)
    yetkiler = models.ManyToManyField(Permission, blank=True)
    @property
    def username(self):
        return self.user.username

    def __str__(self):
        return self.ad

    def update_username(self, new_username, new_password):
        self.user.username = new_username
        self.user.set_password(new_password)
        self.user.save()  

    def get_katildigi_etkinlik_sayisi(self):
        return self.katildigi_etkinlikler.count()
    
class Bildirim(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING,null=True,blank=True,related_name='kullanici')
    etkinlik = models.ForeignKey(Event, on_delete=models.DO_NOTHING, null=True, blank=True)
    etkilesim = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    bildirim_alani = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='bildirimler1')
    bildirim = models.TextField(max_length=255,null=True, blank=True)
    olusturulma_tarihi = models.DateTimeField(default=timezone.now)

haydi/templates/profile/my_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/update_profile.css' %}">
<div class="row">
  <div class="content col-lg-6 "> <!-- Start Content -->
    <div class="card"><!-- Start Card -->
      <div class="row g-0"><!-- Start row g-0 -->
        <div class="col-md-4 sm-8"><!-- Start col-md-4 -->
          <div class="d-flex align-items-center justify-content-center" style="height: 100%;"><!-- Start d-flex -->
            {% if user.profile.profile_img and user.profile.profile_img.url %}
              <img src="{{ user.profile.profile_img.url }}" alt="User Image" style="width: 150px; height: 150px;" class="rounded-start ml-4">
            {% else %}
              
            {% endif %}
          </div><!-- End d-flex -->
        </div><!-- End col-md-4 -->
        <div class="col-md-8 sm-8"><!-- Start col-md-8 -->
          <div class="card-body"><!-- Start card-body -->
            <h5 class="card-title">{{ user.profile.ad|title }} {{ user.profile.soyad|title }}</h5>
            <p class="card-text">@<small>{{user.username}}</small></p>
            pozitif {{pozitif_oy_sayisi}}
            <ul class="list-group list-group-flush">
              {% if user.profile.telefon != None %}
                <li class="list-group-item"><i class="mdi mdi-phone font-size-15 align-middle pe-2 text-primary"></i> {{ user.profile.telefon }}</li>
              {% else %}
                <li class="list-group-item"><i class="mdi mdi-phone font-size-15 align-middle pe-2 text-primary"></i> Telefon Yok</li>
              {% endif %}
              <li class="list-group-item"><i class="mdi mdi-email font-size-15 align-middle pe-2 text-primary"></i> {{ user.profile.email }}</li>
              <li class="list-group-item"><i class="mdi mdi-account-plus font-size-15 align-middle pe-2 text-primary"></i><strong>Katıldığınız Etkinlikler</strong> <span class="badge badge-info">{{ katildigi_etkinlikler.count }}</span></li>
              <li class="list-group-item"><i class="mdi mdi-account-edit font-size-15 align-middle pe-2 text-primary"></i><strong>Oluşturduğunuz Etkinlikler</strong> <span class="badge badge-info">{{ olusturdugu_etkinlikler.count }}</span></li>
            </ul>
            <a href="{% url 'update_profile' %}" class="btn btn-primary">Güncelle</a>
            <button type="button" class="btn btn-primary">Contact</button>
          </div><!-- End card-body -->
        </div><!-- End col-md-8 -->
      </div><!-- End row g-0 -->
    </div><!-- End Card -->
    
    <h1 class="text-center mt-4">Son Etkinliklerim</h1>

    <div class="row justify-content-center">
      {% for etkinlik in son_etkinliklerim %}
      <div class="col-lg-6 col-md-6 col-sm-12 mt-2 d-flex  mb-4">
        <div class="card" style="width: 18rem; height: 100%;">
          <div class="card-body">
            <h5 class="card-title">{{ etkinlik.ad }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ etkinlik.saat }}</h6>
            <p class="card-text">{{ etkinlik.açiklama|safe|truncatechars_html:20 }}</p>
            <a href="{% url 'eventdetail' etkinlik.slug %}" class="card-link"><i class="fa-solid fa-feather"></i> Etkinlik Detay</a>
            <a href="{% url 'yer_detay' etkinlik.mekan.pk %}" class="card-link"><i class="fa-solid fa-shop"></i> Yer Detay</a>
          </div>
        </div>
        <br>
      </div>
      {% endfor %}
    </div>
    
  </div><!-- End Content -->
  <br/>
  <br/>
  <div class="col-lg-3 col-sm-3"  id="takipci">
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-center">
        <button type="button" class="btn btn-info">
          Takip Ettiklerim <span class="badge badge-light">{{ takip_listesi.count }}</span>
        </button>
      </li>
      
      {% for takipci in sayfa %}
      <li class="list-group-item">
        <div class="d-flex align-items-center justify-content-between">
          <a class="ml-2" href="{% url 'show_profile' takipci.username %}">{{ takipci.username }}</a>
          <form method="POST" action="{% url 'takip_et' takipci.pk %}">
            {% csrf_token %}
            <button type="submit" title="Çıkar" id="engel_btn" class="btn btn-link">
              <i class="fa-solid fa-user-minus text-danger mr-4"></i>
            </button>
          </form>
        </div>
      </li>
      {% empty %}
        <li class="list-group-item">Takip ettiğin kimse yok.</li>
      {% endfor %}
    </ul>
    <div class="pagination">
      {% if sayfa.has_previous %}
        <a href="?sayfa={{ sayfa.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
      {% endif %}
      
      {% if sayfa.has_next %}
        <a href="?sayfa={{ sayfa.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
      {% endif %}
    </div>
  </div>
  <div class="col-lg-3 col-sm-3" id="takipci">
    
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-center">
        <button type="button" class="btn btn-info">
          Takipçi Listesi <span class="badge badge-light">{{ takipçi_listesi.count }}</span>
        </button>
      </li>
      
      {% for takipci in takipçi_listesi %}
      <li class="list-group-item ">
        <div class="d-flex align-items-center justify-content-between">
          <a href="{% url 'show_profile' takipci.username %}" class ="ml-4">{{ takipci.username }}</a>
          <form method="POST" action="{% url 'takipciyi_cikar' takipci.pk %}">
            {% csrf_token %}
            <button type="submit" id="engel_btn" title="Kaldır" class="btn btn-link">
              <i class="fa-solid fa-user-minus text-danger mr-4"></i>
            </button>
          </form>
        </div>
      </li>
          
     

          

      {% empty %}
        <li class="list-group-item">Takipçi Bulunmuyor</li>
      {% endfor %}
    </ul>
  </div>
</div>



{% endblock %}

haydi/templates/profile/profili_güncelle.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/update_profile.css' %}">
<div class="container">
  <div class="row">
    
    <div class="col-md-12 col-lg-12 order-md-1">
      <form method="post" enctype="multipart/form-data" class="mx-auto">
        <div class="col-md-8 col-lg-4 mx-auto text-center">
          {% if user.profile.profile_img %}
            <img src="{{ user.profile.profile_img.url }}" alt="User Image" style="width: 150px; height: 150px;" class="rounded-start">
          {% else %}
          yok
          {% endif %}
        <div class="form-group">
          <label for="id_profile_img">Profil Resmi</label>
          <input type="file" class="form-control-file" id="id_profile_img" name="profile_img">
        </div>
        {% if user.profile.profile_img %}
        <div class="form-group">
          <p for="id_clear_profile_img" class="form-check-label center">Profil Resmini Kaldır
            <input type="checkbox" id="id_clear_profile_img" name="clear_profile_img" class="form-check-input ml-4">
          </p>
        </div>
       
        <button type="submit" class="btn btn-danger">Kaldır</button>
      {% else %}
      <button type="submit" class="btn btn-success">Kaydet</button>
      {% endif %}
        
      </div>
      
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_ad">Adınız</label>
              <input type="text" value="{{ form.ad.value }}" class="form-control" name="ad" placeholder="Adınız">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_soyad">Soyadınız</label>
              <input type="text" value="{{ form.soyad.value }}" class="form-control" name="soyad" placeholder="Soyadınız">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_username">Kullanıcı Adınız</label>
              <input type="text" value="{{ form.username.value }}" class="form-control" name="username" placeholder="Kullanıcı Adınız">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_email">Email Adresiniz</label>
              <input type="email" value="{{ form.email.value }}" class="form-control" name="email" placeholder="Email Adresiniz">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_telefon">Telefonunuz</label>
              <input type="text" value="{{ form.telefon.value }}" class="form-control" name="telefon" placeholder="Telefonunuz">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_new_password1">Şifre</label>
              <input type="password" class="form-control" id="id_new_password1" name="new_password1" placeholder="Şifre">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_new_password2">Şifre</label>
              <input type="password" class="form-control" id="id_new_password2" name="new_password2" placeholder="Şifre">
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Kaydet</button>
      </form>
    </div>
  </div>
</div>
</form>
{% endblock %}

haydi/templates/profile/user_not_found.html
<section class="p-0 bg-img cover-background" style="background-image: url(https://bootdey.com/img/Content/bg1.jpg);">
    <div class="container-fluid d-flex flex-column">
        <div class="row align-items-center justify-content-center min-vh-100">
            <div class="col-md-9 col-lg-6 my-5">
                <div class="text-center error-page">
                    <h1 class="mb-0 text-secondary">404</h1>
                    <h2 class="mb-4 text-white">Sorry, something went wrong!</h2>
                    <p class="w-sm-80 mx-auto mb-4 text-white">This page is incidentally inaccessible because of support. We will back very before long much obliged for your understanding</p>
                    <div>
                        <a href="#" class="btn btn-info btn-lg me-sm-2 mb-2 mb-sm-0">Return Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>