etkinlik/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("haydi.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

haydi/urls.py
from django import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
urlpatterns = [
path('', views.home, name='home'),
path('<int:year>/<str:month>/', views.home, name='home'),
path('mekan_ekle/', views.mekanekle, name='mekanekle'),
path('get-ilceler/<int:sehir_id>/', views.get_ilceler, name='get_ilceler'),   
path('eventlist', views.eventlist, name='eventlist'),
path('update_profile', views.update_profile, name='update_profile'),
path('eventdetail/<slug:slug>', views.eventdetail, name='eventdetail'),
path('yer_listesi/', views.yer_listesi, name='yer_listesi'), 
path('yer_detay/<int:pk>', views.yer_detay, name='yer_detay'),
path('arama_sonuclari/', views.arama_sonuclari, name='arama_sonuclari'),
path('etkinlik_ekle', views.etkinlik_ekle, name='etkinlik_ekle'),
path('get-mekanlar/<int:ilce_id>/', views.get_mekanlar, name='get_mekanlar'),
path('register/', views.register, name='register'),
path('login/', views.login_view, name='login'),
path('logout/', views.custom_logout, name='logout'),
path('my_profile/', views.my_profile, name='my_profile'),
path('show_profile/<str:username>/', views.show_profile, name='show_profile'),
path('katilimci_ol/<slug:slug>/', views.katilimci_ol, name='katilimci_ol'),
path('katilmayi_birak/<slug:slug>/', views.katilmayi_birak, name='katilmayi_birak'),
path('etkinlik/<slug:slug>/sil/', views.etkinlik_sil, name='etkinlik_sil'),
path('etkinlik_düzenle/<slug:slug>', views.etkinlik_düzenle, name='etkinlik_düzenle'),
path('mekan_güncelle/<int:mekan_id>', views.mekan_guncelle, name='mekan_güncelle'),
path('mekanlar/', views.sahip_oldugunuz_mekanlar, name='mekanlar'),
path('etkinliklerim/', views.etkinliklerim, name='etkinliklerim'),
path('etkinlikten_at/<slug:slug>/<int:pk>', views.etkinlikten_at, name='etkinlikten_at'),
path('yorum_yap/<slug:slug>/', views.yorum_yap, name='yorum_yap'),
path('yorum_sil/<int:pk>', views.yorum_sil, name='yorum_sil'),
path('cevap_ver/<int:pk>/<slug:slug>', views.cevap_ver, name='cevap_ver'),
path('mekan_sil/<int:pk>', views.mekan_sil, name='mekan_sil'),
path('mekani_ac/<int:pk>', views.mekani_ac, name='mekani_ac'),
path('mekani_kapat/<int:pk>', views.mekani_kapat, name='mekani_kapat'),
path('olumlu_oy/<int:pk>/', views.olumlu_oy, name='olumlu_oy'),
path('olumsuz_oy/<int:pk>/', views.olumsuz_oy, name='olumsuz_oy'),
path('mekan_begeni_durumu/<int:pk>/', views.mekan_begeni_durumu, name='mekan_begeni_durumu'),
path('bildirim_acildi/', views.bildirim_acildi, name='bildirim_acildi'),
path('home', views.home, name='home'),
path('gundetay/<int:day>-<str:month>-<int:year>/', views.gundetay, name='gundetay'),
path('engelle/<int:pk>', views.engelle, name='engelle'),
path('takip_et/<int:pk>', views.takip_et, name='takip_et'),
path('takipciyi_cikar/<int:pk>', views.takipciyi_cikar, name='takipciyi_cikar'),
path('pozitif_oy/<int:pk>',views.profil_pozitif_oy,name="pozitif_oy"),
path('negatif_oy/<int:pk>',views.profil_negatif_oy,name="negatif_oy"),

# path('gundetay/', views.gundetay, name='gundetay'),
# path('gundetay/<str:selected_date>/', views.gundetay_selected, name='gundetay_selected'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haydi/models.py
import datetime
import os
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from cities_light.models import SubRegion, Region
from ckeditor.fields import RichTextField

from django.utils.crypto import get_random_string

def user_directory_path(instance, filename):
    # Dosya adını kullanıcı adı ile değiştir
    ext = filename.split('.')[-1]
    filename = f'{instance.username}_{timezone.now().strftime("%Y-%m-%d-%H-%M-%S")}.{ext}'

    # Dosyanın kaydedileceği klasörü belirle
    folder = f'profile_pics/{instance.username}'

    # Klasörü oluştur
    os.makedirs(folder, exist_ok=True)

    # Tam dosya yolu
    return os.path.join(folder, filename)

    
class Mekan(models.Model):
    adi = models.CharField('Mekan Adı', max_length=20)
    adres = models.CharField(max_length=300)
    telefon_numarasi = models.CharField('Telefon', max_length=11)
    webadresi = models.URLField('Website Adresi')
    email = models.EmailField('Email Adresi')
    sehir = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True, related_name='sehir')
    ilce = models.ForeignKey(SubRegion, on_delete=models.SET_NULL, null=True, blank=True)
    aciklama = models.TextField('Mekan Açıklaması', null=True, blank=True)
    olusturan = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    onayli = models.BooleanField('Onaylı', default=True) # default False olacak deneme için true dedim
    onay_tarihi = models.DateTimeField('Onay Tarihi', null=True, blank=True)
    silindi = models.BooleanField('Silindi',default='False')
    acik = models.BooleanField('Etkinliğe Açık',default=False)
    olumlu_oy = models.PositiveIntegerField(default=0)
    olumlu_oy_kullananlar = models.ManyToManyField(User, related_name='olumlu_oylar',null=True,blank=True)
    olumsuz_oy = models.PositiveIntegerField(default=0)
    olumsuz_oy_kullananlar = models.ManyToManyField(User, related_name='olumsuz_oylar',null=True,blank=True)

    def save(self, *args, **kwargs):
        if self.onayli and not self.onay_tarihi:
            self.onay_tarihi = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.adi

class Event(models.Model):
    ad = models.CharField('Etkinlik Adı', max_length=50)
    baslik = models.CharField('Baslik', max_length=50, null=True, blank=True)
    slug = models.SlugField(unique=True, max_length=100, null=True, blank=True)
    saat = models.TimeField('Saat', null=False, blank=False)
    gün = models.DateTimeField('Etkinlik Günü')
    katilimcilar = models.ManyToManyField(User, related_name='katildigi_etkinlikler', blank=True)
    katilimci_kontrol = models.BooleanField(default=False)
    kontenjan = models.PositiveIntegerField(default=0,null=True,blank=True)
    mekan = models.ForeignKey(Mekan, blank=True, null=True,related_name='etkinlikler', on_delete=models.CASCADE)
    açiklama = RichTextField()
    yönetici = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name='yönetici_event_set')
    silindi = models.BooleanField(default=False)
    takipçiye_özel = models.BooleanField(default=False)
    def get_katilimcilar(self):
        return self.katilimcilar.all()
    def __str__(self):
        return f"{self.ad} ({self.gün.strftime('%d.%m.%Y %H:%M')})"

    def save(self, *args, **kwargs):
        if not self.baslik:  # Başlık boşsa (yeni etkinlik)
            self.baslik = slugify(self.ad)  # Etkinlik adından başlığı oluştur
        if not self.slug:  # Slug boşsa (yeni etkinlik)
            slug = slugify(self.baslik)
            random_string = get_random_string(length=4)  # Rastgele bir dize oluştur
            self.slug = f"{slug}-{random_string}"  # Slug'a rastgele dizeyi ekle
        # if self.katilimci_kontrol:
        #     self.katilimci_sayisi = self.katilimcilar.count()
        super(Event, self).save(*args, **kwargs)
    
    def günü_gecmis(self):
        now = datetime.now()
        event_datetime = datetime.combine(self.gün, self.saat)
        return event_datetime < now
class Yorum(models.Model):
    yorum = models.CharField(max_length=255)
    yorum_sahibi = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='yorumlar')
    silindi = models.BooleanField(default=False)
    def event_ad(self):
        return self.event.ad
class YorumCevap(models.Model):
    cevap = models.CharField(max_length=255,blank=True,null=True)
    yorum = models.ForeignKey(Yorum, on_delete=models.DO_NOTHING, related_name='cevaplar',null=True,blank=True)
    cevapsahibi = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    silindi = models.BooleanField(default=False)

    def __str__(self):
        return self.cevap


from django.contrib.auth.models import Permission
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    ad = models.CharField(max_length=20, verbose_name='ad')
    soyad = models.CharField(max_length=20)
    profile_img = models.ImageField(upload_to=user_directory_path)
    email = models.EmailField(null=True, blank=True)
    telefon = models.CharField(max_length=11, blank=True, null=True)
    kayit_tarihi = models.DateTimeField(auto_now_add=True)
    katildigi_etkinlikler = models.ManyToManyField(Event, related_name='katilimcilar_profil', blank=True)
    olusturdugu_etkinlikler = models.ManyToManyField(Event, related_name='olusturan_profil', blank=True)
    bildirimler = models.ManyToManyField('Bildirim', related_name='bildirim_alani1', blank=True,null=True)
    bildirim_sayisi = models.PositiveIntegerField(default = 0 ,null=True,blank=True,)
    engelli_listesi = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='engelli')
    takip_ettiklerim = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='takip_edilen')
    takipçiler = models.ManyToManyField(User,null=True,blank=True,symmetrical=False,related_name='takipçilerim')
    pozitif_oylar = models.ManyToManyField(User, related_name='pozitif_oylar',null=True,blank=True)
    negatif_oylar = models.ManyToManyField(User, related_name='negatif_oylar',null=True,blank=True)
    yetkiler = models.ManyToManyField(Permission, blank=True)
    @property
    def username(self):
        return self.user.username

    def __str__(self):
        return self.ad

    def update_username(self, new_username, new_password):
        self.user.username = new_username
        self.user.set_password(new_password)
        self.user.save()  

    def get_katildigi_etkinlik_sayisi(self):
        return self.katildigi_etkinlikler.count()
    
class Bildirim(models.Model):
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING,null=True,blank=True,related_name='kullanici')
    etkinlik = models.ForeignKey(Event, on_delete=models.DO_NOTHING, null=True, blank=True)
    etkilesim = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    bildirim_alani = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, related_name='bildirimler1')
    bildirim = models.TextField(max_length=255,null=True, blank=True)
    olusturulma_tarihi = models.DateTimeField(default=timezone.now)

haydi/templates/etkinlik/etkinlik_düzenle.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-block col-md-4 mb-3">Başvuru Oluştur</button>
</form>

{% if form.errors %}
    <div class="alert alert-danger mt-4">
        <ul>
            {% for field in form %}
                {% if field.errors %}
                    <li>{{ field.label }}: {{ field.errors|join:", " }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% endblock content %}

haydi/templates/etkinlik/etkinlik_ekle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container fluid">
    <br/>
    
  
  <script>
      {% if messages %}
          $(document).ready(function() {
              $('#errorModal').modal('show');
          });
      {% endif %}
  </script>
    <center>
      <br/>
      <br/>
      <h1 class="text-center">Etkinlik Oluştur</h1>
      {% if submitted %}
        <p>Mekan Başvurunuz Alınmıştır</p>
        <a href="{% url 'home' %}" class="btn btn-info">Anasayfaya Dön</a>
      {% else %}
        <form method="POST">
          {% csrf_token %}
          <div class="form-group col-md-4 mb-3">
            <input type="text" class="form-control" name="ad" placeholder="Etkinlik Adı">
          </div>
          <div class="form-group col-md-4 mb-3">
            <small class="form-text text-muted">Şehir seçiniz</small>
            {{ form.sehir }}
            {% if errors.sehir %}
              <p class="text-danger">{{ errors.sehir }}</p>
            {% endif %}
          </div>
          <div class="form-group col-md-4 mb-3">
            <small class="form-text text-muted">İlçe seçiniz</small>
            {{ form.ilce }}
            {% if errors.sehir %}
              <p class="text-danger">{{ errors.ilce }}</p>
            {% endif %}
          </div>
          <div class="form-group col-md-4 mb-3">
            {{ form.mekan }}
          </div>
          <div class="form-group col-md-4 mb-3">
            <div class="checkbox-and-input-container">
              <input id="id_katilimci_kontrol" type="checkbox" name="{{ form.katilimci_kontrol.name }}" class="form-check-input" {% if form.katilimci_kontrol.value %}checked{% endif %}>
              <label for="id_katilimci_kontrol" class="form-check-label">
                <span>Katılımcı Kontrolü yap</span>
              </label>
              <input id="katilimciAlan" type="number" name="{{ form.kontenjan.name }}" value="{{ form.kontenjan.value }}" class="form-control" placeholder="Kaç kişi katılabilir?" min="0">
            </div>
          </div>
          <div class="form-group col-md-4 mb-3">
            <div class="checkbox-and-input-container">
              <input id="id_katilimci_kontrol" type="checkbox" name="{{ form.takipçiye_özel.name }}" class="form-check-input" {% if form.katilimci_kontrol.value %}checked{% endif %}>
              <label for="id_katilimci_kontrol" class="form-check-label">
                <span>Takipçiye Özel Yap</span>
              </label>
            </div>
          </div>
          
          
          
          <div class="form-group col-md-4 mb-3">
            {{ form.gün }}
          </div>
          <div class="form-group col-md-4 mb-3">
            {{ form.saat }}
          </div>
          <div class="form-group col-md-4 mb-3">
            <small class="form-text text-muted">Açıklama Giriniz</small>
            {{ form.açiklama }}
        </div>
          <br/>
          <button type="submit" class="btn btn-primary btn-block col-md-4 mb-3">Başvuru Oluştur</button>
        </form>

      {% endif %}
<!-- Modal kodu -->
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="errorModalLabel"><strong>Hata</strong></h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if form.errors %}
          <div class="alert alert-danger" role="alert">
            Formda hatalar var:
            <ul>
              {% for field in form %}
                {% for error in field.errors %}
                  <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                {% endfor %}
              {% endfor %}
            </ul>
          </div>
        {% endif %}
        {% if form.non_field_errors %}
          <div class="alert alert-warning">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
        </div>
      </div>
    </div>
  </div>
  <script>
    // Modalı tetikle
    {% if form.errors or form.non_field_errors %}
      $(document).ready(function() {
        $('#errorModal').modal('show');
      });
    {% endif %}
  </script>
    </center>
  </div>

  <script>
   // İl değiştiğinde ilçe alanını güncelle
// İl değiştiğinde ilçe alanını güncelle
document.getElementById('sehir-select').addEventListener('change', function() {
    var sehirId = this.value;
    var ilceSelect = document.getElementById('ilce-select');
    var mekanSelect = document.getElementById('mekan-select');
  
    // İlçe ve mekan alanlarını boşalt
    ilceSelect.innerHTML = '';
    mekanSelect.innerHTML = '<option value="">---------</option>';
  
    // İlçeleri almak için AJAX isteği gönder
    var xhr = new XMLHttpRequest();
    xhr.open('GET', '/get-ilceler/' + sehirId + '/');
    xhr.onload = function() {
      if (xhr.status === 200) {
        var ilceler = JSON.parse(xhr.responseText);
  
        // İlçe seçeneklerini oluştur
        ilceler.forEach(function(ilce) {
          var option = document.createElement('option');
          option.value = ilce.id;
          option.textContent = ilce.name;
          ilceSelect.appendChild(option);
        });
      }
    };
    xhr.send();
  });
  
  // İlçe değiştiğinde mekan alanını güncelle
  document.getElementById('ilce-select').addEventListener('change', function() {
    var ilceId = this.value;
    var mekanSelect = document.getElementById('mekan-select');
  
    // Mekan alanını boşalt
    mekanSelect.innerHTML = '<option value="">---------</option>';
  
    // Mekanları almak için AJAX isteği gönder
    var xhr = new XMLHttpRequest();
    xhr.open('GET', '/get-mekanlar/' + ilceId + '/');
    xhr.onload = function() {
      if (xhr.status === 200) {
        var mekanlar = JSON.parse(xhr.responseText);
  
        // Mekan seçeneklerini oluştur
        mekanlar.forEach(function(mekan) {
          var option = document.createElement('option');
          option.value = mekan.id;
          option.textContent = mekan.adi;
          mekanSelect.appendChild(option);
        });
      }
    };
    xhr.send();
  });
  </script>
          
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      var katilimciKontrolCheckbox = document.getElementById("id_katilimci_kontrol");
      var katilimciSayisiInput = document.getElementById("katilimciAlan");
    
      // Checkbox durumunu dinle
      katilimciKontrolCheckbox.addEventListener("change", function() {
        if (katilimciKontrolCheckbox.checked) {
          katilimciSayisiInput.style.display = "block";  // Göster
        } else {
          katilimciSayisiInput.style.display = "none";  // Gizle
          katilimciSayisiInput.value = "";  // Boş değer atama
        }
      });
    
      // Sayfa yüklendiğinde kontrol et
      if (!katilimciKontrolCheckbox.checked) {
        katilimciSayisiInput.style.display = "none";  // Gizle
        katilimciSayisiInput.value = "";  // Boş değer atama
      }
    });
  </script>
  
  
{% endblock content %}

haydi/templates/etkinlik/etkinlik_silindi.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap Delete Confirmation Modal</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>

</style>
</head>
<body>
    <div class="text-center">
        <!-- Button HTML (to Trigger Modal) -->
        <a href="#myModal" class="trigger-btn" data-toggle="modal" style="display: none;">Click to Open Confirm Modal</a>
    </div>
    
    <!-- Modal HTML -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>						
                    <h4 class="modal-title w-100">Hata</h4>	
                    {% comment %} <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> {% endcomment %}
                </div>
                <div class="modal-body">
                    <h4 class="modal-title w-100">Bu Etkinlik Silinmiş</h4>
                </div>
                <div class="modal-footer justify-content-center">
                    <a href="{% url 'home' %}" class="btn btn-info">Anasayfaya Dön</a>
                    <a href="{% url 'eventlist' %}" class="btn btn-success">Diğer Etkinliklere Gözat</a>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        $(window).on('load', function() {
            $('.trigger-btn').click();
        });
        
    </script>
{% endblock %}

haydi/templates/etkinlik/mekan_güncelle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-primary btn-block col-md-4 mb-3">Güncelle</button>
</form>
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel"><strong>Bilgi</strong></h5>
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.level_tag }}">
                        
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        
                    </div>
                    {% endfor %}
                {% endif %}
                <div class="modal-footer">
                    <a href="{% url 'yer_detay' mekan.pk %}" class="btn btn-warning">Detaya Dön</a>
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">Güncellenebilir Alanları Gör</button>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        {% if messages %}
            $("#errorModal").modal("show");
        {% endif %}
    });
</script>
{% endblock content %}